"""E2: the evidence snapshot the dashboard reads, with nulls where nothing was observed.

`ui/data/evidence.json`, regenerated by `make ui-data`. One entry per rule:

    {rule_id, skill, text, provenance, trusted, version,
     x: mean_retrieval_score_when_consulted,
     y: exercise_pass_rate,
     size: consult_count,
     citations: [...]}

**The null rule is the important part of this file.** Where a quantity has no observations,
it is `null`, never a number standing in for one. Today `consult_count` is zero for almost
everything, because retrieval only just started emitting, so `x` is null for almost every
rule. The map will be sparse, and that is correct: a dense map today would be fiction, and a
dashboard that renders fiction is worse than one that renders little, because nobody can tell
which they are looking at.

The consumer is told the same thing in the file: `null` means unobserved, and an unobserved
rule belongs at a neutral position rather than at zero. Zero is an observation. Null is not.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

from orchestrator.events import CONSULTATION, EXERCISE_FAIL, EXERCISE_PASS, read as read_events

EVIDENCE = Path("ui") / "data" / "evidence.json"
RULE_LINE = re.compile(r"^(\d+)\.\s+(.*)$", re.MULTILINE)
CITE_KEY = re.compile(r"\[([a-z0-9][a-z0-9-]*)\]")


def _rules_of(skill_dir: Path) -> list[tuple[str, str, list[str]]]:
    """Every numbered rule in a skill, with the citation keys it carries."""
    body = (skill_dir / "SKILL.md").read_text(encoding="utf-8")
    section = re.search(r"^## Method\s*$(.*?)(?=^## |\Z)", body, re.MULTILINE | re.DOTALL)
    if not section:
        return []
    out = []
    for m in RULE_LINE.finditer(section.group(1)):
        n, text = m.group(1), " ".join(m.group(2).split())
        out.append((f"{skill_dir.name}#{n}", text, CITE_KEY.findall(text)))
    return out


def build(registry_root: Path | str = "registry",
          events_path: Path | str | None = None) -> dict:
    root = Path(registry_root)
    events = read_events(events_path) if events_path else read_events()

    # observations, keyed by rule where the event names one and by skill otherwise
    consult_scores: dict[str, list[float]] = {}
    consult_count: dict[str, int] = {}
    selected_count: dict[str, int] = {}
    passes: dict[str, int] = {}
    fails: dict[str, int] = {}

    for e in events:
        skill = e.get("skill")
        rule = e.get("rule_id")
        key = rule or skill
        if not key:
            continue
        if e["event_type"] == CONSULTATION:
            payload = e.get("payload") or {}
            score = payload.get("score")
            consult_count[key] = consult_count.get(key, 0) + 1
            # Retrieval scores EVERY skill on every query, so a raw consultation count is a
            # count of how many lookups were run and is identical across skills. It cannot
            # discriminate. Ranking first is a per-skill outcome, so that is what coverage
            # reads.
            if payload.get("rank") == 1:
                selected_count[key] = selected_count.get(key, 0) + 1
            if isinstance(score, (int, float)):
                consult_scores.setdefault(key, []).append(float(score))
        elif e["event_type"] == EXERCISE_PASS:
            passes[key] = passes.get(key, 0) + 1
        elif e["event_type"] == EXERCISE_FAIL:
            fails[key] = fails.get(key, 0) + 1

    rules = []
    for skill_dir in sorted(p for p in root.iterdir() if p.is_dir()):
        if skill_dir.name.startswith("_") or not (skill_dir / "meta.yaml").is_file():
            continue
        meta = yaml.safe_load((skill_dir / "meta.yaml").read_text(encoding="utf-8")) or {}
        skill = meta.get("name", skill_dir.name)

        for rule_id, text, cites in _rules_of(skill_dir):
            # a rule inherits its skill's observations when nothing named the rule directly
            n = consult_count.get(rule_id, consult_count.get(skill, 0))
            sel = selected_count.get(rule_id, selected_count.get(skill, 0))
            scores = consult_scores.get(rule_id) or consult_scores.get(skill) or []
            p, f = passes.get(skill, 0), fails.get(skill, 0)

            rules.append({
                "rule_id": rule_id,
                "skill": skill,
                "text": text,
                "provenance": meta.get("minted_from"),
                "trusted": bool(meta.get("exercised", False)),
                "version": meta.get("version"),
                # null, not zero. Zero is an observation; null is the absence of one.
                "x": round(sum(scores) / len(scores), 4) if scores else None,
                "y": round(p / (p + f), 4) if (p + f) else None,
                "size": n if n else None,
                "selected": sel if sel else None,
                "citations": cites,
            })

    observed = sum(1 for r in rules if r["x"] is not None)
    return {
        "generated_from": "registry + ui/data/events.jsonl",
        "schema": {
            "x": (
                "mean retrieval score when this rule's skill was consulted; null if never "
                "consulted. Retrieval ranks SKILLS, not rules, so every rule of a consulted "
                "skill inherits that skill's score. Do not read per-rule precision into it: "
                "two rules of one skill are indistinguishable on this axis today."
            ),
            "y": "exercise pass rate for the owning skill; null if never exercised",
            "size": "consultation count; null if never consulted. Identical across skills by construction, because retrieval scores every skill on every query.",
            "selected": "times this skill ranked first in a lookup; null if never. This is the discriminating quantity, and coverage reads it.",
            "null_means": (
                "no observation exists. Render at a neutral gutter position, not at zero. "
                "Zero is an observation that something scored nothing; null is the absence "
                "of any observation, and conflating them turns a sparse map into a "
                "confident wrong one."
            ),
        },
        "counts": {
            "rules": len(rules),
            "rules_with_retrieval_observations": observed,
            "rules_without": len(rules) - observed,
            "events_read": len(events),
        },
        "rules": rules,
    }


SKILLEARN = Path("ui") / "data" / "skillearn.json"

# The dashboard mock was designed against a different schema than the one built. Adapting the
# DATA is cheap and adapting the HTML is not, so this emits the mock's exact shape from the
# same observations, rather than restyling a file that already works.
_EVENT_TYPE_MAP = {
    "mint": "mint",
    "amend": "mint",              # an amend produces a new rule body, which the mock draws as a mint

    "exercise_pass": "pass",
    "exercise_fail": "fail",
    "trust_revoked": "revoke",
    "retrieval_consultation": None,   # not an event the mock renders; it feeds `consults`
    "decision": "deviation",
}



# The dashboard's dimension order. Four carry real observations; four have no data source
# and stay null. A null contributes nothing to the 3D projection, which is the honest
# rendering: an unobserved dimension should not push a node anywhere.
DIMS = ["relevance", "pass_rate", "specificity", "recency",
        "coverage", "risk", "novelty", "stability"]
EMB_DIMS = len(DIMS)


def _embedding(rule: dict, newest: float | None = None, oldest: float | None = None,
               busiest: int | None = None) -> list:
    """emb[8] in the dashboard's dimension order, with null where nothing was observed.

    relevance  mean retrieval score when the rule's skill was consulted
    pass_rate  exercise pass rate for the owning skill
    recency    how recently the skill was exercised, scaled across the registry
    coverage   consultation count, scaled

    specificity, risk, novelty and stability have no data source in this repository. They are
    null rather than zero or a filler value: zero is an observation that something scored
    nothing, and a filler would render as a position the rule does not have.
    """
    sel = rule.get("selected")
    coverage = None
    if sel and busiest:
        coverage = round(min(1.0, sel / busiest), 4)

    recency = None
    ts = rule.get("_exercised_epoch")
    if ts and newest and oldest is not None:
        span = (newest - oldest) or 1.0
        recency = round(max(0.0, min(1.0, (ts - oldest) / span)), 4)

    return [
        rule.get("x"),      # relevance
        rule.get("y"),      # pass_rate
        None,               # specificity
        recency,            # recency
        coverage,           # coverage
        None,               # risk
        None,               # novelty
        None,               # stability
    ]


def build_skillearn(registry_root: Path | str = "registry",
                    events_path: Path | str | None = None) -> dict:
    """The mock's exact shape, from the same observations evidence.json reports."""
    data = build(registry_root, events_path)
    rules = data["rules"]
    index_of = {r["rule_id"]: i for i, r in enumerate(rules)}

    import datetime
    import yaml
    hashes = {}
    exercised_at = {}
    for d in sorted(p for p in Path(registry_root).iterdir() if p.is_dir()):
        mf = d / "meta.yaml"
        if mf.is_file():
            m = yaml.safe_load(mf.read_text(encoding="utf-8")) or {}
            nm = m.get("name", d.name)
            hashes[nm] = m.get("exercised_hash")
            raw = m.get("exercised_at")
            if raw:
                try:
                    exercised_at[nm] = datetime.datetime.fromisoformat(
                        str(raw).replace("Z", "+00:00")).timestamp()
                except Exception:
                    pass

    busiest = max((r.get("selected") or 0) for r in rules) if rules else 0
    stamps = [exercised_at[r["skill"]] for r in rules if r["skill"] in exercised_at]
    newest, oldest = (max(stamps), min(stamps)) if stamps else (None, None)
    for r in rules:
        r["_exercised_epoch"] = exercised_at.get(r["skill"])

    out_rules = [{
        "rule_id": r["rule_id"],
        "skill": r["skill"],
        "text": r["text"],
        "provenance": r["provenance"],
        "trusted": r["trusted"],
        "version": r["version"],
        "consults": r["size"],                  # null when never consulted, per the null rule
        "citations": r["citations"],
        "exercised_hash": hashes.get(r["skill"]),
        "emb": _embedding(r, newest, oldest, busiest),
    } for r in rules]

    events = []
    for e in read_events(events_path) if events_path else read_events():
        mapped = _EVENT_TYPE_MAP.get(e["event_type"])
        if not mapped:
            continue
        rid = e.get("rule_id")
        idx = index_of.get(rid) if rid else None
        if idx is None and e.get("skill"):
            # skill-level event: attribute to that skill's first rule, and say so in the file
            for r_id, i in index_of.items():
                if r_id.startswith(f"{e['skill']}#"):
                    idx = i
                    break
        if idx is None:
            # an event nothing can be attributed to would render against a rule chosen at
            # random, so it is dropped rather than guessed at
            continue
        events.append({
            "t": e["ts"],
            "type": mapped,
            "idx": idx,
            "score": (e.get("payload") or {}).get("score"),
        })

    return {
        "note": (
            "Emitted for the dashboard mock's schema. emb[8] carries observed quantities in "
            "its leading slots and null in the rest; the dimensions are not a learned "
            "embedding and no value is invented to fill the shape. consults is null, never "
            "zero, where a rule has never been consulted. An event whose idx is a skill-level "
            "attribution points at that skill's first rule, because retrieval and exercise "
            "observe skills rather than individual rules."
        ),
        "emb_dims": EMB_DIMS,
        "emb_meaning": DIMS,
        "emb_observed": ["relevance", "pass_rate", "recency", "coverage"],
        "emb_null": ["specificity", "risk", "novelty", "stability"],
        "rules": out_rules,
        "events": events,
    }


def write_skillearn(registry_root: Path | str = "registry",
                    path: Path | str = SKILLEARN,
                    events_path: Path | str | None = None) -> dict:
    data = build_skillearn(registry_root, events_path)
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return data


def write(registry_root: Path | str = "registry", path: Path | str = EVIDENCE,
          events_path: Path | str | None = None) -> dict:
    data = build(registry_root, events_path)
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return data


if __name__ == "__main__":
    from orchestrator.events import write_backfill

    total = write_backfill()
    d = write()
    sk = write_skillearn()
    c = d["counts"]
    print(f"  events.jsonl:  {total} records after backfill")
    print(f"  evidence.json: {c['rules']} rules, "
          f"{c['rules_with_retrieval_observations']} with retrieval observations, "
          f"{c['rules_without']} without")
    print(f"  skillearn.json: {len(sk['rules'])} rules, {len(sk['events'])} events "
          f"in the dashboard mock's shape")
    if c["rules_without"]:
        print(f"  {c['rules_without']} rules carry null for x and size. That is correct today: "
              f"they have not been consulted, and a number there would be invented.")
