"""E2: the evidence snapshot the dashboard reads, with nulls where nothing was observed.

`ui/data/evidence.json`, regenerated by `make ui-data`. One entry per rule:

    {rule_id, skill, text, provenance, trusted, version,
     x: mean_retrieval_score_when_consulted,
     y: exercise_pass_rate,
     size: consult_count,
     citations: [...]}

**The null rule is the important part of this file.** Where a quantity has no observations,
it is `null`, never a number standing in for one. Today `consult_count` is zero for almost
everything, because retrieval only just started emitting, so `x` is null for almost every
rule. The map will be sparse, and that is correct: a dense map today would be fiction, and a
dashboard that renders fiction is worse than one that renders little, because nobody can tell
which they are looking at.

The consumer is told the same thing in the file: `null` means unobserved, and an unobserved
rule belongs at a neutral position rather than at zero. Zero is an observation. Null is not.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

from orchestrator.events import CONSULTATION, EXERCISE_FAIL, EXERCISE_PASS, read as read_events

EVIDENCE = Path("ui") / "data" / "evidence.json"
RULE_LINE = re.compile(r"^(\d+)\.\s+(.*)$", re.MULTILINE)
CITE_KEY = re.compile(r"\[([a-z0-9][a-z0-9-]*)\]")


def _rules_of(skill_dir: Path) -> list[tuple[str, str, list[str]]]:
    """Every numbered rule in a skill, with the citation keys it carries."""
    body = (skill_dir / "SKILL.md").read_text(encoding="utf-8")
    section = re.search(r"^## Method\s*$(.*?)(?=^## |\Z)", body, re.MULTILINE | re.DOTALL)
    if not section:
        return []
    out = []
    for m in RULE_LINE.finditer(section.group(1)):
        n, text = m.group(1), " ".join(m.group(2).split())
        out.append((f"{skill_dir.name}#{n}", text, CITE_KEY.findall(text)))
    return out


def build(registry_root: Path | str = "registry",
          events_path: Path | str | None = None) -> dict:
    root = Path(registry_root)
    events = read_events(events_path) if events_path else read_events()

    # observations, keyed by rule where the event names one and by skill otherwise
    consult_scores: dict[str, list[float]] = {}
    consult_count: dict[str, int] = {}
    passes: dict[str, int] = {}
    fails: dict[str, int] = {}

    for e in events:
        skill = e.get("skill")
        rule = e.get("rule_id")
        key = rule or skill
        if not key:
            continue
        if e["event_type"] == CONSULTATION:
            score = (e.get("payload") or {}).get("score")
            consult_count[key] = consult_count.get(key, 0) + 1
            if isinstance(score, (int, float)):
                consult_scores.setdefault(key, []).append(float(score))
        elif e["event_type"] == EXERCISE_PASS:
            passes[key] = passes.get(key, 0) + 1
        elif e["event_type"] == EXERCISE_FAIL:
            fails[key] = fails.get(key, 0) + 1

    rules = []
    for skill_dir in sorted(p for p in root.iterdir() if p.is_dir()):
        if skill_dir.name.startswith("_") or not (skill_dir / "meta.yaml").is_file():
            continue
        meta = yaml.safe_load((skill_dir / "meta.yaml").read_text(encoding="utf-8")) or {}
        skill = meta.get("name", skill_dir.name)

        for rule_id, text, cites in _rules_of(skill_dir):
            # a rule inherits its skill's observations when nothing named the rule directly
            n = consult_count.get(rule_id, consult_count.get(skill, 0))
            scores = consult_scores.get(rule_id) or consult_scores.get(skill) or []
            p, f = passes.get(skill, 0), fails.get(skill, 0)

            rules.append({
                "rule_id": rule_id,
                "skill": skill,
                "text": text,
                "provenance": meta.get("minted_from"),
                "trusted": bool(meta.get("exercised", False)),
                "version": meta.get("version"),
                # null, not zero. Zero is an observation; null is the absence of one.
                "x": round(sum(scores) / len(scores), 4) if scores else None,
                "y": round(p / (p + f), 4) if (p + f) else None,
                "size": n if n else None,
                "citations": cites,
            })

    observed = sum(1 for r in rules if r["x"] is not None)
    return {
        "generated_from": "registry + ui/data/events.jsonl",
        "schema": {
            "x": (
                "mean retrieval score when this rule's skill was consulted; null if never "
                "consulted. Retrieval ranks SKILLS, not rules, so every rule of a consulted "
                "skill inherits that skill's score. Do not read per-rule precision into it: "
                "two rules of one skill are indistinguishable on this axis today."
            ),
            "y": "exercise pass rate for the owning skill; null if never exercised",
            "size": "consultation count; null if never consulted",
            "null_means": (
                "no observation exists. Render at a neutral gutter position, not at zero. "
                "Zero is an observation that something scored nothing; null is the absence "
                "of any observation, and conflating them turns a sparse map into a "
                "confident wrong one."
            ),
        },
        "counts": {
            "rules": len(rules),
            "rules_with_retrieval_observations": observed,
            "rules_without": len(rules) - observed,
            "events_read": len(events),
        },
        "rules": rules,
    }


def write(registry_root: Path | str = "registry", path: Path | str = EVIDENCE,
          events_path: Path | str | None = None) -> dict:
    data = build(registry_root, events_path)
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return data


if __name__ == "__main__":
    from orchestrator.events import write_backfill

    total = write_backfill()
    d = write()
    c = d["counts"]
    print(f"  events.jsonl:  {total} records after backfill")
    print(f"  evidence.json: {c['rules']} rules, "
          f"{c['rules_with_retrieval_observations']} with retrieval observations, "
          f"{c['rules_without']} without")
    if c["rules_without"]:
        print(f"  {c['rules_without']} rules carry null for x and size. That is correct today: "
              f"they have not been consulted, and a number there would be invented.")
